#
# DO NOT MODIFY!!!!
# This file is automatically generated by racc 1.4.5
# from racc grammer file "lib/future/query_grammar.racc".
#

require 'racc/parser'


class QueryStringParser < Racc::Parser

module_eval <<'..end lib/future/query_grammar.racc modeval..id5be7ced690', 'lib/future/query_grammar.racc', 130

Negation = Struct.new(:child)
Unary = Struct.new(:op, :child)
BinaryAnd = Struct.new(:left, :right)
BinaryOr = Struct.new(:left, :right)
KeyValExpr = Struct.new(:key, :values)
RangeKeyValExpr = Struct.new(:key, :values)
SortExpr = Struct.new(:key, :direction)

require 'strscan'
def parse(str)
  @yydebug = true if $DEBUG
  @lexer = Lexer.new(str)
  do_parse
end

def next_token
  @lexer.next_token
end

..end lib/future/query_grammar.racc modeval..id5be7ced690

##### racc 1.4.5 generates ###

racc_reduce_table = [
 0, 0, :racc_error,
 1, 39, :_reduce_1,
 2, 40, :_reduce_2,
 3, 40, :_reduce_3,
 1, 40, :_reduce_4,
 1, 40, :_reduce_5,
 3, 40, :_reduce_6,
 3, 40, :_reduce_7,
 1, 40, :_reduce_8,
 1, 40, :_reduce_9,
 2, 40, :_reduce_10,
 1, 43, :_reduce_none,
 1, 43, :_reduce_12,
 3, 41, :_reduce_13,
 3, 41, :_reduce_14,
 3, 42, :_reduce_15,
 1, 44, :_reduce_16,
 1, 44, :_reduce_17,
 1, 44, :_reduce_18,
 1, 44, :_reduce_19,
 1, 44, :_reduce_20,
 1, 44, :_reduce_21,
 1, 44, :_reduce_22,
 1, 44, :_reduce_23,
 1, 44, :_reduce_24,
 1, 44, :_reduce_25,
 1, 46, :_reduce_26,
 1, 46, :_reduce_27,
 1, 46, :_reduce_28,
 1, 46, :_reduce_29,
 1, 46, :_reduce_30,
 1, 46, :_reduce_31,
 1, 46, :_reduce_32,
 1, 46, :_reduce_33,
 1, 46, :_reduce_34,
 2, 45, :_reduce_35,
 3, 45, :_reduce_36,
 3, 45, :_reduce_37,
 3, 45, :_reduce_38,
 1, 45, :_reduce_39,
 3, 48, :_reduce_40,
 2, 48, :_reduce_41,
 1, 48, :_reduce_42,
 1, 49, :_reduce_43,
 1, 49, :_reduce_44,
 1, 49, :_reduce_45,
 1, 49, :_reduce_46,
 1, 49, :_reduce_47,
 1, 49, :_reduce_48,
 1, 49, :_reduce_49,
 1, 49, :_reduce_50,
 1, 49, :_reduce_51,
 1, 49, :_reduce_52,
 1, 49, :_reduce_53,
 1, 50, :_reduce_54,
 1, 50, :_reduce_55,
 1, 47, :_reduce_56,
 3, 47, :_reduce_57,
 1, 47, :_reduce_58,
 1, 47, :_reduce_59,
 2, 51, :_reduce_60,
 2, 52, :_reduce_61,
 1, 52, :_reduce_none,
 0, 54, :_reduce_63,
 7, 53, :_reduce_64 ]

racc_reduce_n = 65

racc_shift_n = 94

racc_action_table = [
    42,    42,    32,    77,    43,    43,    50,    50,    42,    42,
    72,    73,    43,    43,    50,    50,    72,    73,    81,    82,
    42,    34,    46,    46,    43,    87,    50,    77,    42,    42,
    46,    46,    43,    43,    50,    48,    48,    77,    86,    77,
    92,    89,    46,    48,    48,    72,    73,    77,    31,    69,
    46,    35,   nil,   nil,   nil,    48,   nil,     8,   nil,   nil,
   nil,    17,    21,    48,    27,    30,     2,     5,     6,    10,
    11,    13,    15,    19,    23,    26,    29,     1,     4,     9,
   nil,    12,    14,    16,    20,    24,     8,    37,    38,   nil,
    17,    21,   nil,    27,    30,     2,     5,     6,    10,    11,
    13,    15,    19,    23,    26,    29,     1,     4,     9,     8,
    12,    14,    16,    20,    24,   nil,     8,    42,   nil,   nil,
   nil,    43,    44,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,     9,   nil,    12,    14,    16,    20,    24,     9,    41,
    12,    14,    16,    20,    24,     8,    37,    38,   nil,    17,
    21,   nil,    27,    30,     2,     5,     6,    10,    11,    13,
    15,    19,    23,    26,    29,     1,     4,     9,    54,    12,
    14,    16,    20,    24,     8,    37,    38,   nil,    17,    21,
   nil,    27,    30,     2,     5,     6,    10,    11,    13,    15,
    19,    23,    26,    29,     1,     4,     9,   nil,    12,    14,
    16,    20,    24,     8,   nil,   nil,   nil,    17,    21,   nil,
    27,    30,     2,     5,     6,    10,    11,    13,    15,    19,
    23,    26,    29,     1,     4,     9,   nil,    12,    14,    16,
    20,    24,     8,    37,    38,   nil,   -65,   -65,   nil,   nil,
    42,   nil,    42,   nil,    43,    44,    43,    44,   nil,   nil,
   nil,   nil,   nil,   nil,     9,   nil,    12,    14,    16,    20,
    24,     8,    41,   nil,    41,    17,    21,   nil,    27,    30,
     2,     5,     6,    10,    11,    13,    15,    19,    23,    26,
    29,     1,     4,     9,   nil,    12,    14,    16,    20,    24,
     8,   nil,   nil,   nil,    17,    21,   nil,    27,    30,     2,
     5,     6,    10,    11,    13,    15,    19,    23,    26,    29,
     1,     4,     9,   nil,    12,    14,    16,    20,    24,     8,
   nil,   nil,   nil,    17,    21,   nil,    27,    30,     2,     5,
     6,    10,    11,    13,    15,    19,    23,    26,    29,     1,
     4,     9,   nil,    12,    14,    16,    20,    24,    55,   nil,
    58,    42,    60,    62,   nil,    43,    44,   nil,    42,   nil,
   nil,    59,    43,    44,   nil,    64,    65,    66,    67,    68,
    56,    57,    55,    41,    58,   nil,    60,    62,   nil,   nil,
    41,   nil,   nil,   nil,   nil,    59,   nil,   nil,   nil,    64,
    65,    66,    67,    68,    56,    57 ]

racc_action_check = [
    92,    90,     7,    76,    92,    90,    92,    90,    77,    48,
    40,    40,    77,    48,    77,    48,    74,    74,    63,    63,
    32,    12,    92,    90,    32,    76,    32,    47,    46,    50,
    77,    48,    46,    50,    46,    92,    90,    78,    74,    91,
    91,    80,    32,    77,    48,    75,    75,    88,     3,    35,
    46,    18,   nil,   nil,   nil,    32,   nil,    21,   nil,   nil,
   nil,    21,    21,    46,    21,    21,    21,    21,    21,    21,
    21,    21,    21,    21,    21,    21,    21,    21,    21,    21,
   nil,    21,    21,    21,    21,    21,    22,    22,    22,   nil,
    22,    22,   nil,    22,    22,    22,    22,    22,    22,    22,
    22,    22,    22,    22,    22,    22,    22,    22,    22,    71,
    22,    22,    22,    22,    22,   nil,    70,    44,   nil,   nil,
   nil,    44,    44,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    71,   nil,    71,    71,    71,    71,    71,    70,    44,
    70,    70,    70,    70,    70,    33,    33,    33,   nil,    33,
    33,   nil,    33,    33,    33,    33,    33,    33,    33,    33,
    33,    33,    33,    33,    33,    33,    33,    33,    33,    33,
    33,    33,    33,    33,    39,    39,    39,   nil,    39,    39,
   nil,    39,    39,    39,    39,    39,    39,    39,    39,    39,
    39,    39,    39,    39,    39,    39,    39,   nil,    39,    39,
    39,    39,    39,     9,   nil,   nil,   nil,     9,     9,   nil,
     9,     9,     9,     9,     9,     9,     9,     9,     9,     9,
     9,     9,     9,     9,     9,     9,   nil,     9,     9,     9,
     9,     9,    36,    36,    36,   nil,    36,    36,   nil,   nil,
    73,   nil,    72,   nil,    73,    73,    72,    72,   nil,   nil,
   nil,   nil,   nil,   nil,    36,   nil,    36,    36,    36,    36,
    36,    37,    73,   nil,    72,    37,    37,   nil,    37,    37,
    37,    37,    37,    37,    37,    37,    37,    37,    37,    37,
    37,    37,    37,    37,   nil,    37,    37,    37,    37,    37,
    38,   nil,   nil,   nil,    38,    38,   nil,    38,    38,    38,
    38,    38,    38,    38,    38,    38,    38,    38,    38,    38,
    38,    38,    38,   nil,    38,    38,    38,    38,    38,     0,
   nil,   nil,   nil,     0,     0,   nil,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,   nil,     0,     0,     0,     0,     0,    34,   nil,
    34,    41,    34,    34,   nil,    41,    41,   nil,    31,   nil,
   nil,    34,    31,    31,   nil,    34,    34,    34,    34,    34,
    34,    34,    59,    41,    59,   nil,    59,    59,   nil,   nil,
    31,   nil,   nil,   nil,   nil,    59,   nil,   nil,   nil,    59,
    59,    59,    59,    59,    59,    59 ]

racc_action_pointer = [
   317,   nil,   nil,    43,   nil,   nil,   nil,    -3,   nil,   201,
   nil,   nil,    16,   nil,   nil,   nil,   nil,   nil,    51,   nil,
   nil,    55,    84,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   356,    18,   143,   337,    49,   230,   259,   288,   172,
     7,   349,   nil,   nil,   115,   nil,    26,    24,     7,   nil,
    27,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   361,
   nil,   nil,   nil,   -17,   nil,   nil,   nil,   nil,   nil,   nil,
   114,   107,   240,   238,    13,    42,     0,     6,    34,   nil,
    16,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    44,   nil,
    -1,    36,    -2,   nil ]

racc_action_default = [
   -65,   -33,   -19,   -65,   -34,   -20,   -21,   -65,    -8,   -65,
   -22,   -26,   -65,   -27,   -17,   -28,   -23,    -9,   -65,   -29,
   -24,   -65,    -1,   -30,   -25,    -4,   -31,   -16,    -5,   -32,
   -18,   -65,   -65,   -65,   -65,   -65,    -2,   -65,   -65,   -10,
   -13,   -65,   -11,   -12,   -65,   -39,   -65,   -14,   -65,   -56,
   -65,   -58,   -59,   -62,    -3,   -49,   -46,   -47,   -50,   -65,
   -48,   -15,   -45,   -42,   -53,   -51,   -52,   -43,   -44,    94,
    -6,    -7,   -65,   -65,   -65,   -35,   -65,   -65,   -60,   -61,
   -65,   -54,   -55,   -41,   -37,   -38,   -36,   -57,   -63,   -40,
   -65,   -65,   -65,   -64 ]

racc_goto_table = [
    47,    22,    40,    61,    18,    83,    90,    45,   nil,   nil,
    33,   nil,    74,   nil,    76,    75,    78,    45,   nil,   nil,
    45,   nil,    36,   nil,   nil,   nil,    79,   nil,    80,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    70,    71,
   nil,   nil,   nil,    84,    85,    88,   nil,   nil,    45,    45,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    91,   nil,
    93 ]

racc_goto_check = [
     9,     2,     7,    10,     1,    12,    16,     5,   nil,   nil,
     2,   nil,     7,   nil,     9,     7,     9,     5,   nil,   nil,
     5,   nil,     2,   nil,   nil,   nil,     5,   nil,    10,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     2,     2,
   nil,   nil,   nil,     7,     7,     9,   nil,   nil,     5,     5,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     9,   nil,
     9 ]

racc_goto_pointer = [
   nil,     4,     1,   nil,   nil,   -24,   nil,   -29,   nil,   -32,
   -31,   nil,   -58,   nil,   nil,   nil,   -82 ]

racc_goto_default = [
   nil,   nil,    39,    25,    28,    53,     3,   nil,     7,   nil,
   nil,    63,   nil,    49,    51,    52,   nil ]

racc_token_table = {
 false => 0,
 Object.new => 1,
 :STRING_LITERAL => 2,
 :BI_AND => 3,
 :BI_OR => 4,
 :SEPARATOR => 5,
 :WORD => 6,
 :NOT_OP => 7,
 :RANGE_OP => 8,
 :SET => 9,
 :TAG => 10,
 :USER => 11,
 :GROUP => 12,
 :TYPE => 13,
 :AUTHOR => 14,
 :SIZE => 15,
 :DATE => 16,
 :LENGTH => 17,
 :WIDTH => 18,
 :HEIGHT => 19,
 :PAGES => 20,
 :WORDS => 21,
 :BITRATE => 22,
 :RATING => 23,
 "(" => 24,
 ")" => 25,
 :SORT => 26,
 :DELETED => 27,
 :NAME => 28,
 :SOURCE => 29,
 :REFERRER => 30,
 :NEW => 31,
 :OLD => 32,
 :BIG => 33,
 :SMALL => 34,
 :DESC => 35,
 :ASC => 36,
 :UN_OP => 37 }

racc_use_result_var = true

racc_nt_base = 38

Racc_arg = [
 racc_action_table,
 racc_action_check,
 racc_action_default,
 racc_action_pointer,
 racc_goto_table,
 racc_goto_check,
 racc_goto_default,
 racc_goto_pointer,
 racc_nt_base,
 racc_reduce_table,
 racc_token_table,
 racc_shift_n,
 racc_reduce_n,
 racc_use_result_var ]

Racc_token_to_s_table = [
'$end',
'error',
'STRING_LITERAL',
'BI_AND',
'BI_OR',
'SEPARATOR',
'WORD',
'NOT_OP',
'RANGE_OP',
'SET',
'TAG',
'USER',
'GROUP',
'TYPE',
'AUTHOR',
'SIZE',
'DATE',
'LENGTH',
'WIDTH',
'HEIGHT',
'PAGES',
'WORDS',
'BITRATE',
'RATING',
'"("',
'")"',
'SORT',
'DELETED',
'NAME',
'SOURCE',
'REFERRER',
'NEW',
'OLD',
'BIG',
'SMALL',
'DESC',
'ASC',
'UN_OP',
'$start',
'start',
'query',
'keyval_expression',
'sort_expression',
'string',
'discrete_key',
'discrete_values',
'range_key',
'range_values',
'sort_values',
'sort_key',
'sort_order',
'range_unary_expr',
'range_basic_expr',
'range_expr',
'@1']

Racc_debug_parser = false

##### racc system variables end #####

 # reduce 0 omitted

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 15
  def _reduce_1( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 19
  def _reduce_2( val, _values, result )
 result = Negation.new(val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 20
  def _reduce_3( val, _values, result )
 result = val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 21
  def _reduce_4( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 22
  def _reduce_5( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 23
  def _reduce_6( val, _values, result )
 result = BinaryAnd.new(val[0], val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 24
  def _reduce_7( val, _values, result )
 result = BinaryOr.new(val[0], val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 25
  def _reduce_8( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 26
  def _reduce_9( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 27
  def _reduce_10( val, _values, result )
 result = BinaryAnd.new(val[0], val[1])
   result
  end
.,.,

 # reduce 11 omitted

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 31
  def _reduce_12( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 35
  def _reduce_13( val, _values, result )
 result = KeyValExpr.new(val[0], val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 36
  def _reduce_14( val, _values, result )
 result = RangeKeyValExpr.new(val[0], val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 40
  def _reduce_15( val, _values, result )
 result = val[2]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 44
  def _reduce_16( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 45
  def _reduce_17( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 46
  def _reduce_18( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 47
  def _reduce_19( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 48
  def _reduce_20( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 49
  def _reduce_21( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 50
  def _reduce_22( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 51
  def _reduce_23( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 52
  def _reduce_24( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 53
  def _reduce_25( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 57
  def _reduce_26( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 58
  def _reduce_27( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 59
  def _reduce_28( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 60
  def _reduce_29( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 61
  def _reduce_30( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 62
  def _reduce_31( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 63
  def _reduce_32( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 64
  def _reduce_33( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 65
  def _reduce_34( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 71
  def _reduce_35( val, _values, result )
 result = Negation.new(val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 72
  def _reduce_36( val, _values, result )
 result = val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 73
  def _reduce_37( val, _values, result )
 result = BinaryAnd.new(val[0], val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 74
  def _reduce_38( val, _values, result )
 result = BinaryOr.new(val[0], val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 75
  def _reduce_39( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 79
  def _reduce_40( val, _values, result )
 result = val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 80
  def _reduce_41( val, _values, result )
 result = SortExpr.new(val[0], val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 81
  def _reduce_42( val, _values, result )
 result = SortExpr.new(val[0], 'asc')
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 85
  def _reduce_43( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 86
  def _reduce_44( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 87
  def _reduce_45( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 88
  def _reduce_46( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 89
  def _reduce_47( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 90
  def _reduce_48( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 91
  def _reduce_49( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 92
  def _reduce_50( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 93
  def _reduce_51( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 94
  def _reduce_52( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 95
  def _reduce_53( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 99
  def _reduce_54( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 100
  def _reduce_55( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 106
  def _reduce_56( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 107
  def _reduce_57( val, _values, result )
 result = val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 108
  def _reduce_58( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 109
  def _reduce_59( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 113
  def _reduce_60( val, _values, result )
 result = Unary.new(val[0], val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 119
  def _reduce_61( val, _values, result )
 result = Unary.new(val[0], val[1])
   result
  end
.,.,

 # reduce 62 omitted

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 124
  def _reduce_63( val, _values, result )
 result = BinaryAnd.new(val[0], val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/future/query_grammar.racc', 125
  def _reduce_64( val, _values, result )
 result = BinaryOr.new(val[0], val[2])
   result
  end
.,.,

 def _reduce_none( val, _values, result )
  result
 end

end   # class QueryStringParser


class Lexer
  class StateDef < Struct.new(:tokens)
    def on(re, &block)
      self.tokens << [re, block]
    end
  end
  def self.def_state(name, &block)
    statedef = StateDef.new([])
    statedef.instance_eval(&block)
    tokens = statedef.tokens
    #puts "State: #{name}, tokens: #{tokens.map{|x,y| x}.join(", ")}"
    define_method("scan_#{name}") do
      break [false, "$end"] if @sscan.eos?
      #puts "scan_#{name}"
      r = tokens.each do |regexp, block|
        #puts "Scanning against #{regexp}"
        if match = @sscan.scan(regexp)
          if block
            if (ret = block.call(match))
              #puts "RETURNING #{ret.inspect}" if $DEBUG
              @state = ret.pop if ret[2]
              break ret
            else
              break next_token
            end
          else
            break [match, match]
          end
        end
      end
      r or raise "cannot lex at #{@sscan.rest}"
    end
  end

  def initialize(str)
    @state = :normal
    @sscan = StringScanner.new(str)
  end

  def next_token
    send("scan_#{@state}")
  end

# lexer def
  def_state(:normal) do
    on(/\s+/){ nil } # ignore
    on(/!|~/){|op| [:NOT_OP, op]}
    on(/(\(|\))/)
    on(/"[^"]+"/){|str| [:STRING_LITERAL, str[1..-2]] }
    on(/:/) { [:SEPARATOR, ':'] }
    on(/&|and\b/){ [:BI_AND, '&'] }
    on(/\||or\b/){ [:BI_OR, '|'] }
    %w[set deleted tag user group type author sort new old big small source referrer asc desc name  size date length width height pages words bitrate rating].each do |qualifier|
      on(/#{qualifier}\b/i){ [qualifier.upcase.to_sym, qualifier] }
    end
    on(/(<|>|<=|>=|=|==)/){|op| [:RANGE_OP, op] }
    on(/[^ \t|&~()]+/){|str| [:WORD, str.strip]}
  end
end


if __FILE__ == $0
  require 'pp'
  parser = QueryStringParser.new
  print "Enter expression (^D or q to quit): "
  until (line = gets.to_s.strip).empty? || line == "q"
    ast = parser.parse(line)
    pp ast
    print "Enter expression (^D or q to quit): "
  end
end
